NotesRecognition/NotesRecognition/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('user/', include(('user_handler.urls','user_handler'),namespace='user'))
]

NotesRecognition/user_handler/urls.py
from django.contrib import admin
from django.urls import path
from .views import *
urlpatterns = [
    path('', index),
    path('profile/', profile, name='profile'),
    path('register/',register, name='register'),
    path('login/',login, name='login')
]

NotesRecognition/notes_handler/models.py
from django.db import models

# Create your models here.

NotesRecognition/user_handler/models.py
from django.db import models

# Create your models here.

NotesRecognition/NotesRecognition/views.py

from django.http import HttpRequest, HttpResponse
from django.shortcuts import render, redirect

def index(request:HttpRequest)->HttpResponse:
    return render(request,'index.html')



NotesRecognition/notes_handler/views.py
from django.shortcuts import render

# Create your views here.

NotesRecognition/user_handler/views.py
from django.shortcuts import render, redirect
from django.http import HttpRequest, HttpResponse
from django.contrib.auth.decorators import login_required

def check_auth(request):
    if request.user.is_authenticated:
        return 1#HttpResponse("Пользователь авторизован", status=200)
    else:
        return 0#redirect('user:login') 

def index(request:HttpRequest)->HttpResponse:
    return redirect('user:profile')
    """if check_auth(request):
        return redirect('user:profile')
    else:
        return redirect('user:login')"""

#@login_required
def profile(request:HttpRequest)->HttpResponse:
    return HttpResponse('123')

def login(request:HttpRequest)->HttpResponse:
    return render(request,'login.html')

def register(request:HttpRequest)->HttpResponse:
    return render(request,'register.html')

NotesRecognition/templates/inc/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
{% block head %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/inc/base.css' %}">
    <script src="{% static 'jquery-3.7.1.min'%}"></script>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Rubik:ital,wght@0,300..900;1,300..900&display=swap" rel="stylesheet">
    {% block title %}
        <title>Document</title>
    {% endblock %}
</head>
{% endblock %}

{% block style %}

{% endblock %}

{% block body %}
<body>
    
</body>
{% endblock %}

{% block script %}

{% endblock %}
</html>

NotesRecognition/templates/inc/basic.html
{% extends 'inc/base.html' %}
{% load static %}

{% block title %}
    <title></title>
{% endblock %}

{% block style %}
    <link rel="stylesheet" href="{% static 'css/' %}">
{% endblock %}

{% block body %}

    {% include 'inc/topnav.html' %}

{% endblock %}

{% block script %}

{% endblock %}

NotesRecognition/templates/inc/topnav.html
{% extends 'inc/base.html' %}
{% load static %}

{% block title %}
    <title></title>
{% endblock %}

{% block style %}
    <link rel="stylesheet" href="{% static 'css/inc/topnav.css' %}">
{% endblock %}

{% block body %}

    <div class="topnav">
        <div class="nav-button">
            <button>кнопОЧКА</button>
            <button>КнОпОчКа</button>
            <button>КНЫПОЧКА</button>
        </div>
    </div>

{% endblock %}

{% block script %}

{% endblock %}

NotesRecognition/templates/index.html
{% extends 'inc/base.html' %}
{% load static %}

{% block title %}
    <title>index</title>
{% endblock %}

{% block style %}
    <link rel="stylesheet" href="{% static 'css/' %}">
{% endblock %}

{% block body %}

    {% include 'inc/topnav.html' %}
    
    

{% endblock %}

{% block script %}

{% endblock %}

NotesRecognition/templates/login.html
{% extends 'inc/base.html' %}
{% load static %}

{% block title %}
    <title>Авторизация</title>
{% endblock %}

{% block style %}
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
{% endblock %}

{% block body %}
    <div class="container">
        <div class="title">Авторизация</div>
        <form class="form">
            <input type="text" placeholder="Логин" required>
            <input type="password" placeholder="Пароль" required>
            <button class="login-button" type="submit">Войти</button>
        </form>
        <p class="no-account">Нет аккаунта? <a href='{% url "user:register" %}'>Регистрация</a>.</p>
    </div>
{% endblock %}

{% block script %}

{% endblock %}

NotesRecognition/templates/profile.html
{% extends 'inc/base.html' %}
{% load static %}

{% block title %}
    <title>Профиль</title>
{% endblock %}

{% block style %}
    <link rel="stylesheet" href="{% static 'css/profile.css' %}">
{% endblock %}

{% block body %}
    {% include 'inc/topnav.html' %}
    <div class="profile-container">
        <div class="header">
            <div class="username">Логин пользователя</div>
        </div>
        <div class="audio-container">
            <h2>Полученные аудио</h2>
            <ul>
            </ul>
        </div>
        <div class="images-container">
            <h2>Загруженные изображения</h2>
            <div class="images-grid">
            </div>
        </div>
    </div>
{% endblock %}

{% block script %}

{% endblock %}

NotesRecognition/templates/register.html
{% extends 'inc/base.html' %}
{% load static %}

{% block title %}
    <title>Регистрация</title>
{% endblock %}

{% block style %}
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
{% endblock %}

{% block body %}
    <div class="container">
        <div class="title">Регистрация</div>
        <form class="form">
            <input type="text" placeholder="Логин" required>
            <input type="password" placeholder="Пароль" required>
            <button class="login-button" type="submit">Зарегистрироваться</button>
        </form>
        <p class="no-account">Уже есть аккаунт? <a href='{% url "user:login" %}'>Авторизоваться</a>.</p>
    </div>
{% endblock %}

{% block script %}

{% endblock %}